### ISSUE TITLE
 TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string

### ISSUE THREAD

**Issue by Anexo** [lululeon/sourcerer#1]
Hi, my goal is to use your source code, to be able to call R scripts from node.js

I cloned your project, created the data folders and subfolders. On the staging folder I added a sample.txt file with some text. Then I ran:

```
npm install
npm start
```

But I am getting this error:
```
> sourcerer@1.0.0 start C:\Users\..\00rscript
> node src/index.js

Invoking R script... at: C:\Users\..\00rscript\src\sourcerer-core\wordcloud.R
Finished with error: TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at normalizeSpawnArguments (child_process.js:399:3)
    at spawn (child_process.js:532:38)
    at Promise (C:\Users\..\00rscript\src\index.js:12:19)
    at new Promise (<anonymous>)
    at callR (C:\Users\..\00rscript\src\index.js:10:10)
    at Object.<anonymous> (C:\Users\..\00rscript\src\index.js:31:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
```

I think, looking at the logs, that the script is not able to call my R launcher, but I am a bit lost. Would you mind helping me, to get it to run?

**Comment by lululeon** [comment]
Hi @Anexo , I'm not on my usual development box right now to replicate your error perfectly, but you need  the following files to run the project.

## 1) a `.env` file, at the top level of your folder, with the keys:
```
# path to the R executable on your machine (full path to rscript.exe on windows)
RSCRIPT=

# the path to the base directory / working directory for your r scripts:
# this will be passed in to the invoked r script
RBASEDIR=
```

## 2) a `src/sourcerer-core/config.yml` file, with at minimum the keys:
```
default:
  datadir: C:\path\to\a\folder\for\data\files
```
This particular project uses a data folder with _inputs_, _outputs_ and _staging_ subfolders.

for more information on how config files can be created for your R project, see: https://cran.r-project.org/web/packages/config/vignettes/introduction.html

Hope this helps. I should probably stick this in the readme but I did not expect anyone to see and use this project! Good luck and let me know how it goes! Let me know if I can be of more help.

**Comment by Anexo** [comment]
Thanks for your help
